// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloWorldGreeterClient is the client API for HelloWorldGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloWorldGreeterClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type helloWorldGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloWorldGreeterClient(cc grpc.ClientConnInterface) HelloWorldGreeterClient {
	return &helloWorldGreeterClient{cc}
}

func (c *helloWorldGreeterClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/HelloWorldGreeter/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldGreeterServer is the server API for HelloWorldGreeter service.
// All implementations must embed UnimplementedHelloWorldGreeterServer
// for forward compatibility
type HelloWorldGreeterServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedHelloWorldGreeterServer()
}

// UnimplementedHelloWorldGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedHelloWorldGreeterServer struct {
}

func (UnimplementedHelloWorldGreeterServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedHelloWorldGreeterServer) mustEmbedUnimplementedHelloWorldGreeterServer() {}

// UnsafeHelloWorldGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloWorldGreeterServer will
// result in compilation errors.
type UnsafeHelloWorldGreeterServer interface {
	mustEmbedUnimplementedHelloWorldGreeterServer()
}

func RegisterHelloWorldGreeterServer(s grpc.ServiceRegistrar, srv HelloWorldGreeterServer) {
	s.RegisterService(&HelloWorldGreeter_ServiceDesc, srv)
}

func _HelloWorldGreeter_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldGreeterServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloWorldGreeter/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldGreeterServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloWorldGreeter_ServiceDesc is the grpc.ServiceDesc for HelloWorldGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloWorldGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HelloWorldGreeter",
	HandlerType: (*HelloWorldGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _HelloWorldGreeter_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/test.proto",
}
